### ISSUE TITLE
Cross-series regex queries are too strict

### ISSUE THREAD

**Issue by ross-nordstrom** [influxdb/influxdb#1039]
My use case is I have many multi-column series, all named `xxx_yyy_zzz` where xxx/yyy/zzz are references I use to index the series. The structure of these series may change over time as the metrics I store (columns) change or become obsolete. The result is some series may or may not have a given metric, e.g. `MetricA`.

What I want to do is find a summary of all of `xxx`'s `MetricA` with a query like:
```
SELECT MEAN(MetricA) FROM /^xxx_.*?_.*?$/ WHERE time < t2 AND time > t1
==> Error! Field "MetricA" doesn't exist in series "xxx_y1y1y1_z1z1z1"
```

I think it would be reasonable to expect the query to simply return empty data for the series that don't have that field/column. An alternative, reasonable, behavior would be to "skip" those series and just return data for the series which have the desired field/column.

A workaround would be for me to change my data model and split it to be many more single-column series, each having the metric it's tracking in the series name (e.g. `xxx_yyy_zzz_MetricA`). This seems like a bit of a kludge to me though.

Thoughts? Does this feature exist but I just didn't see it in the documentation? Is it on the roadmap? Is there a deeper concept of "metadata" in Influx beyond just the series name.

**Comment by leesjensen** [comment]
I hit this same problem. It seems unexpected that no error is returned if a series doesn't exist in the queried timeframe, but it returns an error if a metric doesn't exist. I need to be able to add and remove columns as my system matures. It doesn't seem like an "error" that needs "suppressing". Just return none/null for the value just like is done when the series doesn't exist for the entire time frame.

I guess I could go to a single column per series as the OP proposed, but then I really begin to question what is the point of columns?

**Comment by leesjensen** [comment]
This seems to be worse than I previously thought. It is not using the timeframe when checking if the column exists.

Here is what I have observed:

1. All queried series must have at least one entry for an explicitly queried column or you get an error.
2. It doesn't matter if you are querying a timeframe where only series with the column will return results. If any series doesn't have the column you get an error.
3. If you use a `*` instead of a explicit column then it will return `none` values for the missing columns.

Because `*` works properly it seems like this is just a bug. If it can handle it when all columns are selected then it should be able to handle it when a specific column is selected.

**Comment by inthecloud247** [comment]
+1 agree with @leesjensen on this.

I'm definitely finding this error behavior to be unexpected and frustrating. 

Would be great to have an option to suppress errors on regex timeseries queries when columns are missing.

**Comment by inthecloud247** [comment]
Hm I wonder if this is now fixed in the current 0.9.0 rc release:

https://github.com/influxdb/influxdb/pull/1813

**Comment by languitar** [comment]
I also desperately need a solutuion for this. Having a system evolve constantly affects the fields contained in series. Some way to still get around this is needed very much for regex queries.
