### ISSUE TITLE
tags not returned in query result

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#1696]
I create 2 records like this:
```json
'{"points": [{"timestamp": 1422921600000, "tags": {"pk": "pk1"}, "values": {"value": 1}, "name": "my.test", "precision": "ms"}, {"timestamp": 1423008000000, "tags": {"pk": "pk2"}, "values": {"value": 2}, "name": "my.test", "precision": "ms"}], "precision": "ms", "database": "processed"}'
```
There are 2 tags one for each record, now I query the series with `'select * from my.test'` and this is what is returned:

```json
'{"results":[{"rows":[{"name":"my.test","columns":["time","value"],"values":[["2015-02-04T00:00:00Z",2],["2015-02-03T00:00:00Z",1]]}]}]}'
```

There is no mention of tags.

**Comment by pauldix** [comment]
This is fixed by #1632 and in rc3

**Comment by dashesy** [comment]
I tried both rc3 and rc4 and I still do not get tags back, of course now it is using `fields` instead of `values` (nice change BTW):

```json
'{"points": [{"fields": {"value": 1}, "tags": {"pk": "pk1"}, "name": "my.test", "timestamp": 1422921600000, "precision": "ms"}, {"fields": {"value": 2}, "tags": {"pk": "pk2"}, "name": "my.test", "timestamp": 1423008000000, "precision": "ms"}], "precision": "ms", "database": "processed"}'
```
and it returns `series` (also a better name) but still no `tags` there:
```json
'{"results":[{"series":[{"name":"my.test","columns":["time","value"],"values":[["2015-02-03T00:00:00Z",1],["2015-02-04T00:00:00Z",2]]}]}]}
```

**Comment by dashesy** [comment]
It seems tags are not used, `select value from my.test where pk=pk1` returns empty and `select value from my.test` also does not return tags.

**Comment by otoolep** [comment]
@dashesy -- can you please provide a complete script, which uses `curl`, that demonstrates this issue?

**Comment by dashesy** [comment]
Here is what I did to see latest master:

```bash
go get -u -f ./...
go build ./...
rm ~/xdev/gocodez/bin/influxd
~/xdev/gocodez/bin/influx -config /home/dashesy/influxdb.conf
```

Then build db:
```bash
curl -G 'http://localhost:8086/query' --data-urlencode "q=create database mydb"
curl -G 'http://localhost:8086/query' --data-urlencode "q=CREATE RETENTION POLICY mypolicy ON mydb duration 7d REPLICATION 1 DEFAULT"
```

Then add 2 records:
```bash
curl -XPOST 'http://localhost:8086/write' -d '{"points": [{"fields": {"value": 1}, "tags": {"pk": "pk1"}, "name": "test", "timestamp": 1422921600000, "precision": "ms"}, {"fields": {"value": 2}, "tags": {"pk": "pk2"}, "name": "test", "timestamp": 1423008000000, "precision": "ms"}], "precision": "ms", "database": "mydb"}'
```

Then query:
```bash
curl -G 'http://localhost:8086/query' --data-urlencode "q=select value from test" --data-urlencode "db=mydb
```

And this is the results (no tags):
```json
{"results":[{"series":[{"name":"test","columns":["time","value"],"values":[["2015-02-03T00:00:00Z",1],["2015-02-04T00:00:00Z",2]]}]}]}
```

This was for the sake of this test but when I use my Pandas library [here](https://github.com/dashesy/pandas-tsdb) I see same results.

**Comment by otoolep** [comment]
I am seeing this with RC4. @pauldix

**Comment by pauldix** [comment]
@dashesy Can you try this again with RC6? Also, if you want the tags returned, you'll have to group by them either explicitly:

```
select value from foo group by someTag
```

Or do this

```
select value from foo group by *
```

**Comment by dashesy** [comment]
@pauldix Yes it works now! I can now start using InfluxDB more seriously, thanks.
Looking at the docs [here](http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html#querying-data-using-the-http-api) I think the docs should explain how tags are treated, that only those that get mentioned in `group by` or `where` clause will be returned (if this is your design intention). I like this minimalist design. Since the only valid identifier after select (other than regexp) is `value` another way would be something like: `select value, tags from foo` to use `group by` with something more useful like time bins.

**Comment by pauldix** [comment]
@dashesy good to hear. I added issue #1798 which would take care of this. I think that'll give the expected result since it sounds like that's what you ultimately wanted. Was a series for each of those tag keys.

**Comment by KrishnaPG** [comment]
I am encountering the same problem (with 0.9.1 stable version), and trying to get the RC6 as suggested above - but couldn't find it in the downloads page [here](https://influxdb.com/download/index.html)

Is it the Version 0.9.3 (Nightly) that has this fix?

**Comment by KrishnaPG** [comment]
I am sorry - please ignore my previous question. I was checking the results in the admin (web) interface and it was only showing the fields (and not tags) in the html table. But when looked at the curl results, looks like the data has the tags specified properly in the stable version (0.9.1). Thanks for supporting it.
