### ISSUE TITLE
Trouble clustering 3 influxdb instances

### ISSUE THREAD

**Issue by kicombs** [influxdb/influxdb#2140]
We have deployed 3 instances of influxdb at the same time with the following configs:
```
# Welcome to the InfluxDB configuration file.

# If hostname (on the OS) doesn't return a name that can be resolved by the other
# systems in the cluster, you'll have to set the hostname to an IP or something
# that can be resolved here.

hostname = "InfluxDB1IP"

reporting-disabled = true

# Controls certain parameters that only take effect until an initial successful
# start-up has occurred.

[initialization]
join-urls = "http://influxDB1IP:Port,http://influxDB2IP:Port,http://influxDB3IP:Port"

# Control authentication
[authentication]
enabled = false

[logging]
file   = "/var/vcap/sys/log/influxdb/influxdb.log"
write-tracing = true
raft-tracing = true

[statistics]
enabled = false
database = "_internal"
retention-policy = "default"
write-interval = "1m"

# Configure the admin server
[admin]
enabled = false
port = 8083

# Configure the http api
[api]
#ssl-port = 8087    # Ssl support is enabled if you set a port and cert
#ssl-cert = "../cert.pem"

# connections will timeout after this amount of time. Ensures that clients that misbehave
# and keep alive connections they don't use won't end up connection a million times.
# However, if a request is taking longer than this to complete, could be a problem.
read-timeout = "5s"

[input_plugins]

#  [input_plugins.udp]
#  enabled = true
#  port = 4444
#  database = "test"

# Configure the Graphite servers
#[[graphite]]
#protocol = "TCP"
#enabled = true
#address = "192.168.0.1"
#port = 2003
#database = "graphite_tcp"  # store graphite data in this database
#name-position = "last"
#name-separator = "-"

#[[graphite]]
#protocol = "udP"
#enabled = true
#address = "192.168.0.2"
#port = 2005

# Configure collectd server
#[collectd]
#enabled = true
#address = "192.168.0.3"
#port = 25827
#database = "collectd_database"
#typesdb = "foo-db-type"

# Broker configuration
[broker]
# The broker port should be open between all servers in a cluster.
# However, this port shouldn't be accessible from the internet.
port = 8086

# Where the broker logs are stored. The user running InfluxDB will need read/write access.
dir  = "/var/vcap/store/influxdb/broker"

election-timeout = "5s"

[data]
dir = "/var/vcap/store/influxdb/db"
retention-auto-create = false
retention-check-enabled = true
retention-check-period = "5m"

[continuous_queries]
disable = false

[cluster]
dir = "/var/vcap/store/influxdb/cluster"
```
Our replication count is 3.

The 3 instances will all start up, but we cannot create a database using the interactive shell. The error we receive on each of the influxdb instances:
```
> show databases
name: databases
---------------
name

> create database bla
ERR: not leader
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
```

Are we missing any configs for this? We noticed that the data and broker directories exist, but they contain no data other than .meta

**Comment by toddboom** [comment]
@kicombs you should only include the URL of the first node in the `join-urls` parameter, and only on the 2nd and 3rd nodes. give that a try and let us know if it gets the cluster initialized properly.

**Comment by kicombs** [comment]
We've deployed with the join-urls configured as you describe.  We got the same results.   We can't determine which node is the leader as all are rejecting connections with the ERR: not leader message when attempting to create the database.    We also don't see any messages in the log or stdout related to the cluster / raft.   Note that we do have "raft-tracing = true" in the config file.

**Comment by cboggs** [comment]
@kicombs, did you remove the raft directory before restarting with the new config? Technically your raft config got written to disk with all nodes listed as peers, so the config is ignored on the next startup no matter what it's changed to. :-) If you remove the raft data on disk and restart, it should behave correctly.

**Comment by toddboom** [comment]
@kicombs i agree with what @cboggs said - let us know if that doesn't resolve it. also, are you building from master or using a package?

one final thing that's probably not the issue, but can you confirm that the hostnames you're using in the `join-urls` all resolve correctly from each machine in the cluster?
