### ISSUE TITLE
[master] test run fails

### ISSUE THREAD

**Issue by dennisjac** [influxdb/influxdb#2946]
I'm in the process of creating a spec file to produce an rpm that conforms to common filesystem standards. I'm almost done and the everything works fine except that I'd like to hook up the tests as well but they fail. The first thing I see is this:

```
[dennis@nexus influxdb]$ go test -v ./...
# github.com/influxdb/influxdb/influxql
influxql/functions_test.go:8:2: cannot find package "github.com/davecgh/go-spew/spew" in any of:
	/usr/lib/golang/src/github.com/davecgh/go-spew/spew (from $GOROOT)
	/home/dennis/gocode/src/github.com/davecgh/go-spew/spew (from $GOPATH)
FAIL	github.com/influxdb/influxdb/influxql [setup failed]
# github.com/influxdb/influxdb/meta
influxql/functions_test.go:8:2: cannot find package "github.com/davecgh/go-spew/spew" in any of:
	/usr/lib/golang/src/github.com/davecgh/go-spew/spew (from $GOROOT)
	/home/dennis/gocode/src/github.com/davecgh/go-spew/spew (from $GOPATH)
FAIL	github.com/influxdb/influxdb/meta [setup failed]
# github.com/influxdb/influxdb/services/graphite
influxql/functions_test.go:8:2: cannot find package "github.com/davecgh/go-spew/spew" in any of:
	/usr/lib/golang/src/github.com/davecgh/go-spew/spew (from $GOROOT)
	/home/dennis/gocode/src/github.com/davecgh/go-spew/spew (from $GOPATH)
FAIL	github.com/influxdb/influxdb/services/graphite [setup failed]
# github.com/influxdb/influxdb/services/opentsdb
influxql/functions_test.go:8:2: cannot find package "github.com/davecgh/go-spew/spew" in any of:
	/usr/lib/golang/src/github.com/davecgh/go-spew/spew (from $GOROOT)
	/home/dennis/gocode/src/github.com/davecgh/go-spew/spew (from $GOPATH)
FAIL	github.com/influxdb/influxdb/services/opentsdb [setup failed]
```

I can fix this manually by running "go get github.com/davecgh/go-spew/spew" but that is not mentioned in the build instructions.

A bit later I see this:
```
=== RUN TestPointsWriter_WritePoints
[write] 2015/06/11 22:41:32 write failed for shard 13 on node 1: a failure
[write] 2015/06/11 22:41:32 write failed for shard 13 on node 2: a failure
[write] 2015/06/11 22:41:32 write failed for shard 13 on node 3: a failure
[write] 2015/06/11 22:41:32 write failed for shard 11 on node 1: a failure
[write] 2015/06/11 22:41:32 write failed for shard 11 on node 2: a failure
[write] 2015/06/11 22:41:32 write failed for shard 11 on node 3: a failure
[write] 2015/06/11 22:41:32 write failed for shard 15 on node 1: a failure
[write] 2015/06/11 22:41:32 write failed for shard 17 on node 1: a failure
[write] 2015/06/11 22:41:32 write failed for shard 23 on node 2: a failure
[write] 2015/06/11 22:41:32 write failed for shard 25 on node 2: a failure
[write] 2015/06/11 22:41:32 write failed for shard 27 on node 2: a failure
[write] 2015/06/11 22:41:32 write failed for shard 27 on node 3: a failure
[write] 2015/06/11 22:41:32 write failed for shard 29 on node 2: a failure
[write] 2015/06/11 22:41:32 write failed for shard 29 on node 3: a failure
[write] 2015/06/11 22:41:32 write failed for shard 31 on node 1: a failure
[write] 2015/06/11 22:41:32 write failed for shard 31 on node 2: a failure
[write] 2015/06/11 22:41:32 write failed for shard 33 on node 1: a failure
[write] 2015/06/11 22:41:32 write failed for shard 33 on node 2: a failure
[write] 2015/06/11 22:41:32 write failed for shard 35 on node 3: a failure
[write] 2015/06/11 22:41:32 write failed for shard 37 on node 3: a failure
[write] 2015/06/11 22:41:32 write failed for shard 43 on node 1: a failure
[write] 2015/06/11 22:41:32 write failed for shard 43 on node 2: a failure
[write] 2015/06/11 22:41:32 write failed for shard 43 on node 3: a failure
[write] 2015/06/11 22:41:32 write failed for shard 45 on node 1: a failure
[write] 2015/06/11 22:41:32 write failed for shard 45 on node 2: a failure
[write] 2015/06/11 22:41:32 write failed for shard 45 on node 3: a failure
[write] 2015/06/11 22:41:32 write failed for shard 47 on node 1: a failure
[write] 2015/06/11 22:41:32 write failed for shard 49 on node 1: a failure
--- PASS: TestPointsWriter_WritePoints (0.00s)
```
It looks like there are errors yet the test seems to pass anyway. Is this intentional or is there a buf in this test?

**Comment by btashton** [comment]
@dennisjac you might want to check out #1098 I have a copr repo ready with the dependency packages that should meet upstream requirements for Fedora. I stopped working on this because things were moving around too much in InfluxDB. I am a packager so I am happy to start back up again if you get something ready.

**Comment by otoolep** [comment]
The automatic fetch of the test packages has been fixed by this commit in the docs:

https://github.com/influxdb/influxdb/commit/a78fef940c207d1993e2881a66e9ca1711d492f8

**Comment by dennisjac** [comment]
The -t flag fixed the package errors but write failures are still present.

**Comment by otoolep** [comment]
@dennisjac -- those errors are expected, see this test case:

https://github.com/influxdb/influxdb/blob/master/cluster/points_writer_test.go#L113
