### ISSUE TITLE
Installation of deb fails on Debian Squeeze

### ISSUE THREAD

**Issue by davidfuhr** [influxdb/influxdb#3430]
Installation of the deb file fails on Debian Squeeze:

```sh
$ sudo dpkg -i influxdb_0.9.1_amd64.deb 
Selecting previously deselected package influxdb.
(Reading database ... 52358 files and directories currently installed.)
Unpacking influxdb (from influxdb_0.9.1_amd64.deb) ...
Setting up influxdb (0.9.1) ...
dpkg (subprocess): unable to execute installed post-installation script (/var/lib/dpkg/info/influxdb.postinst): Exec format error
dpkg: error processing influxdb (--install):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 influxdb
```

As a workaround I added a shebang (`#!/bin/bash`) to `/var/lib/dpkg/info/influxdb.postinst` and ran `dpkg --configure -a` which completed the installation:

```sh
$ sudo dpkg --configure -a
Setting up influxdb (0.9.1) ...
update-rc.d: using dependency based boot sequencing
update-rc.d: using dependency based boot sequencing
```

Heres the system information:

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 6.0.10 (squeeze)
Release:	6.0.10
Codename:	squeeze
```

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/commit/82ec6e5e17fdf4f5a825fe6b3674e0c9befb5a78

**Comment by otoolep** [comment]
Reference showing shebang in post-install files:

http://askubuntu.com/questions/260978/add-custom-steps-to-source-packages-debian-package-postinst

**Comment by km-cc** [comment]
Problem still exists in 0.9.4.1:

dpkg -i influxdb_0.9.4.1_amd64.deb 
(Reading database ... 41506 files and directories currently installed.)
Preparing to replace influxdb 0.9.4.1 (using influxdb_0.9.4.1_amd64.deb) ...
Unpacking replacement influxdb ...
Setting up influxdb (0.9.4.1) ...
dpkg (subprocess): unable to execute installed post-installation script (/var/lib/dpkg/info/influxdb.postinst): Exec format error
dpkg: error processing influxdb (--install):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 influxdb
