### ISSUE TITLE
[0.9.0] EBS data overwrite

### ISSUE THREAD

**Issue by DaveBlooman** [influxdb/influxdb#3689]
Im using a script to attach an EBS volume when my instance, using 0.8, my volume would be available and data could be written to the disk.  In 0.9, when the volume attaches, it overwrites all data on the volume, defeating the point of this process.  Is there any check or option that is done by InfluxDB at start up that could be causing this?

**Comment by beckettsean** [comment]
> In 0.9, when the volume attaches, it overwrites all data on the volume, defeating the point of this process. 

Meaning that on startup, InfluxDB 0.9 zeroes out the directory? Or that when you start writing to the databases the prior files are overwritten with new, mostly empty files? Just trying to understand exactly what is happening with 0.9.

**Comment by beckettsean** [comment]
What version of 0.9 are you running? Single node?

**Comment by DaveBlooman** [comment]
On startup it zeros out the directory.  

Im using version 0.9.0-1.

Single node

**Comment by beckettsean** [comment]
I would strongly advice upgrading to 0.9.2, or waiting for 0.9.3 later this week. The 0.9.0 release has a number of issues that have been addressed in more recent builds. 

Can you reproduce with a more recent version?

**Comment by DaveBlooman** [comment]
OK, on the latest version, it is working, though annoyingly I still have issues with the admin interface in #3688 which has stopped me from upgrading, thanks for the help.
