### ISSUE TITLE
Issue with InfluxDB client writing date to InfluxDB 0.9.3

### ISSUE THREAD

**Issue by nooproblem** [influxdb/influxdb#4185]
Go version: 1.4.2
Go environment: OSX 10.9.5 and Windows 8.1
InfluxDB version: 0.9.3 (the latest tutum/influxdb docker container)

I have found the following issue when following the Getting Started guide for the influxdb/influxdb/client:

```go
pts[i] = client.Point{
 Measurement: "shapes",
 Tags: map[string]string{
  "color": strconv.Itoa(rand.Intn(len(colors))),
  "shape": strconv.Itoa(rand.Intn(len(shapes))),
 },
 Fields: map[string]interface{}{
  "value": rand.Intn(sampleSize),
 },
 Time: time.Now(),
 Precision: "s",
}
```
```
pts[i]: {shapes map[color:2 shape:3] 2015-09-21 17:15:55.224001927 +0100 BST map[value:6] s }
```
When using the writePoints function, the time value seems to be correct when inserting time.Now() into the name field of the client Point struct (above). However, when the using the influxdb/influxdb/client to post to the InfluxDB API, the date 01/01/1970 00:00:01 is inserted into the database (below).
```
time	color	shape	value
1970-01-01T00:00:01.442852155Z	"0"	"2"	411
```
I am able to replicate this issue when using the client in Windows and OSX environments. I have not tried Go 1.5.1 or a more recent version of InfluxDB (i.e. 0.9.4.1) yet. I am not yet able to determine whether the issue exists in the client or the InfluxDB API.

Your thoughts / advice will be greatly appreciated.

**Comment by rkuchan** [comment]
@nooproblem,

Trying to reproduce the error. Could you send all the code that you used to get there?

Thank you!

**Comment by nooproblem** [comment]
@rkuchan,

Thank you very much for your reply comment.

Please find below the code taken from the Getting Started guide for the influxdb/influxdb/client:

```go
//Following this guide: https://github.com/influxdb/influxdb/tree/master/client

package main

import (
	"fmt"
	"log"
	"math/rand"
	"net/url"
	"strconv"
	"time"
	//"encoding/json"

	"github.com/influxdb/influxdb/client"
)

const (
	MyHost        = "192.168.99.100"
	MyPort        = 8086
	MyDB          = "square_holes"
	MyMeasurement = "shapes"
)

func main() {

	u, err := url.Parse(fmt.Sprintf("http://%s:%d", MyHost, MyPort))
	if err != nil {
		log.Fatal(err)
	}

	conf := client.Config{
		URL:      *u,
		Username: "",
		Password: "",
	}

	con, err := client.NewClient(conf)
	if err != nil {
		log.Fatal(err)
	}

	dur, ver, err := con.Ping()
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Happy as a Hippo! %v, %s", dur, ver)

	createDB(con)

	writePoints(con)

	countRecords(con)

	last10Shapes(con)
}

func queryDB(con *client.Client, cmd string) (res []client.Result, err error) {

	q := client.Query{
		Command:  cmd,
		Database: MyDB,
	}

	if response, err := con.Query(q); err == nil {
		if response.Error() != nil {
			return res, response.Error()
		}
		res = response.Results
	}
	return
}

func createDB(con *client.Client) {

	_, err := queryDB(con, fmt.Sprintf("create database %s", MyDB))
	if err != nil {
		log.Fatal(err)
	}
}

func writePoints(con *client.Client) {

	var (
		shapes     = []string{"circle", "rectangle", "square", "triangle"}
		colors     = []string{"red", "blue", "green"}
		sampleSize = 1000
		pts        = make([]client.Point, sampleSize)
	)

	p := fmt.Println

	rand.Seed(42)
	for i := 0; i < sampleSize; i++ {
		pts[i] = client.Point{
			Measurement: "shapes",
			Tags: map[string]string{
				"color": strconv.Itoa(rand.Intn(len(colors))),
				"shape": strconv.Itoa(rand.Intn(len(shapes))),
			},
			Fields: map[string]interface{}{
				"value": rand.Intn(sampleSize),
			},
			Time:      time.Now(),
			Precision: "s",
		}

		p("time.Now", time.Now)

		p("pts[i]", pts[i])
	}

	bps := client.BatchPoints{
		Points:          pts,
		Database:        MyDB,
		RetentionPolicy: "default",
	}

	//p(bps)

	_, err := con.Write(bps)
	if err != nil {
		log.Fatal(err)
	}
}

func countRecords(con *client.Client) {

	q := fmt.Sprintf("select count(%s) from %s", "value", MyMeasurement)

	res, err := queryDB(con, q)
	if err != nil {
		log.Fatal(err)
	}

	count := res[0].Series[0].Values[0][1]
	log.Printf("Found a total of `%v records", count)
}

func last10Shapes(con *client.Client) {

	q := fmt.Sprintf("select * from %s limit %d", MyMeasurement, 20)

	res, err := queryDB(con, q)
	if err != nil {
		log.Fatal(err)
	}

	for i, row := range res[0].Series[0].Values {
		t, err := time.Parse(time.RFC3339, row[0].(string))
		if err != nil {
			log.Fatal(err)
		}
		//val, err := row[1].(json.Number).Int64()
		val := row[1].(string)
		//log.Printf("[%2d] %s: %03d\n", i, t.Format(time.Stamp), val)
		log.Printf("[%2d] %s: %s\n", i, t.Format(time.Stamp), val)
	}
}
```
When querying the database through the web UI (select * from shapes), the following query results are produced:
```
shapes
time	color	shape	value
1970-01-01T00:00:01.442933308Z	"1"	"3"	105
1970-01-01T00:00:01.442933308Z	"0"	"0"	429
1970-01-01T00:00:01.442933308Z	"2"	"3"	272
1970-01-01T00:00:01.442933308Z	"2"	"2"	267
1970-01-01T00:00:01.442933308Z	"1"	"2"	95
1970-01-01T00:00:01.442933308Z	"0"	"2"	411
1970-01-01T00:00:01.442933308Z	"2"	"0"	899
1970-01-01T00:00:01.442933308Z	"1"	"1"	487
1970-01-01T00:00:01.442933308Z	"0"	"3"	693
1970-01-01T00:00:01.442933308Z	"1"	"0"	178
1970-01-01T00:00:01.442933308Z	"2"	"1"	299
1970-01-01T00:00:01.442933308Z	"0"	"1"	628
```
This is confirmed when using the last10Shapes function:
```
2015/09/22 15:48:28 [ 0] Jan  1 00:00:01: 0
2015/09/22 15:48:28 [ 1] Jan  1 00:00:01: 2
2015/09/22 15:48:28 [ 2] Jan  1 00:00:01: 1
2015/09/22 15:48:28 [ 3] Jan  1 00:00:01: 0
2015/09/22 15:48:28 [ 4] Jan  1 00:00:01: 2
2015/09/22 15:48:28 [ 5] Jan  1 00:00:01: 0
2015/09/22 15:48:28 [ 6] Jan  1 00:00:01: 2
2015/09/22 15:48:28 [ 7] Jan  1 00:00:01: 1
2015/09/22 15:48:28 [ 8] Jan  1 00:00:01: 2
2015/09/22 15:48:28 [ 9] Jan  1 00:00:01: 0
2015/09/22 15:48:28 [10] Jan  1 00:00:01: 1
2015/09/22 15:48:28 [11] Jan  1 00:00:01: 1
```
Your thoughts / advice will of course be greatly appreciated.

**Comment by rkuchan** [comment]
Thank you! Could you run the following query and pass on the output?

`SELECT * FROM shapes GROUP BY * LIMIT 100`

**Comment by mjdesa** [comment]
@nooproblem Just ran the code you gave me and I'm getting timestamps,

```
> select * from shapes limit 10
name: shapes
------------
time				color	shape	value
2015-09-22T21:14:35.372490993Z	2	3	668
2015-09-22T21:14:35.372532906Z	0	3	345
2015-09-22T21:14:35.372545404Z	0	0	128
2015-09-22T21:14:35.37255223Z	1	1	967
2015-09-22T21:14:35.372558905Z	0	0	652
2015-09-22T21:14:35.372565457Z	0	0	601
2015-09-22T21:14:35.372571863Z	2	0	82
2015-09-22T21:14:35.372578346Z	0	0	275
2015-09-22T21:14:35.372585095Z	1	1	2
2015-09-22T21:14:35.372591523Z	1	3	679
```

Try upgrading to go 1.5 and version version 0.9.4+

**Comment by aspcartman** [comment]
@mjdesa I'm having the same problem using 0.9.4.1 influxdb and go 1.5.1

**Comment by aspcartman** [comment]
I fixed it by removing "precision" field from my point.

**Comment by nooproblem** [comment]
Hi,

Thank you very much for your help.

I can also confirm this is fixed when removing the precision field.

**Comment by vrecan** [comment]
I just got bitten by this issue, why was this issue closed when it wasn't fixed? We are sending in data with ms precision and removing the precision field doesn't sound like a good solution to the problem. Also anyone upgrading can hit this bug.

**Comment by vrecan** [comment]
Does the new version auto detect precession or is that just not a supported thing anymore?

**Comment by beckettsean** [comment]
@vrecan what version are you using?

Write precision is supported but is not autodetected. It must be supplied with each write statement or the system will default to nanosecond precision.
