### ISSUE TITLE
TSM1: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#4513]
Started with https://github.com/influxdb/influxdb/issues/4365#issuecomment-149476888

Hi,

I still have this issue, with

version 0.9.5-nightly-66a31ee, branch master, commit 66a31ee9bcd9b5e0f5cc7a2f0b2ceda17f386e49, built '2015-10-20T04:00:43+0000'

My configuration : https://gist.github.com/Issif/0893c15e2cd75156d694

Error logs : https://gist.github.com/Issif/f9b77a2f2aab812696b2

And a tree in shard directory :

.
└── [4.0K Oct 20 10:18]  default
    ├── [4.0K Oct 20 10:18]  1
    │   ├── [ 18M Oct 20 10:18]  0000001.tsm1
    │   ├── [ 45K Oct 20 10:18]  0000002.tsm1
    │   ├── [5.9K Oct 20 10:18]  0000003.tsm1
    │   ├── [ 36K Oct 20 10:18]  0000004.tsm1
    │   ├── [   0 Oct 20 10:18]  0000004.tsm1.check
    │   ├── [2.1M Oct 20 10:18]  _00007.wal
    │   ├── [2.2M Oct 20 10:18]  _00008.wal
    │   ├── [2.0M Oct 20 10:18]  _00009.wal
    │   ├── [2.2M Oct 20 10:18]  _00010.wal
    │   ├── [2.2M Oct 20 10:18]  _00011.wal
    │   ├── [1.6M Oct 20 10:18]  _00012.wal
    │   ├── [2.1M Oct 20 10:18]  _00013.wal
    │   ├── [1.7M Oct 20 10:18]  _00014.wal
    │   ├── [ 988 Oct 20 10:18]  fields
    │   ├── [ 14M Oct 20 10:18]  ids
    │   └── [ 12M Oct 20 10:18]  series
    └── [4.0K Oct 20 10:18]  3
        ├── [5.5K Oct 20 10:18]  0000001.tsm1
        ├── [ 200 Oct 20 10:18]  fields
        ├── [3.0K Oct 20 10:18]  ids
        └── [2.7K Oct 20 10:18]  series

It crashes after few seconds each time (started with no data again).

cc @jwilder @Issif

**Comment by jwilder** [comment]
I can reproduce.  Working on a fix.

**Comment by jwilder** [comment]
Fixed by #4504

**Comment by Issif** [comment]
Hi,

I'm sorry, i still have this issue with last nightly (and fresh install without previous data) : https://gist.github.com/Issif/5bb1763d6f0d4c21cb80

**Comment by otoolep** [comment]
@jwilder -- any ideas?

I am re-opening the issue, but let me know if this is another issue and we can track it there.

**Comment by jwilder** [comment]
This panic is caused by writing `NaN` float values.  #4587 should fix this.

**Comment by jwilder** [comment]
Fixed by #4587
